In [2]:
import pandas as pd
import os

# 如果data文件夹不存在，自动创建
if not os.path.exists("./data"):
    os.makedirs("./data")

sample_json_str = '''
{"article_link": "https://www.huffingtonpost.com/entry/versace-black-code_us_5861fbefe4b0de3a08f600d5", "headline": "former versace store clerk sues over secret 'black code' for minority shoppers", "is_sarcastic": 0}
{"article_link": "https://www.huffingtonpost.com/entry/roseanne-revival-review_us_5ab3a497e4b054d118e04365", "headline": "the 'roseanne' revival catches up to our thorny political mood, for better and worse", "is_sarcastic": 0}
{"article_link": "https://www.theonion.com/mom-starting-to-fear-son-s-only-friend-is-imaginary-1819576460", "headline": "mom starting to fear son's only friend is imaginary", "is_sarcastic": 1}
'''

# 写入json文件
with open("./data/Sarcasm_Headlines_Dataset.json","w",encoding="utf-8") as f:
    f.write(sample_json_str)

# 讲义核心读取代码
json_read = pd.read_json("./data/Sarcasm_Headlines_Dataset.json", orient="records", lines=True)
display(json_read)

,article_link,headline,is_sarcastic
0,https://www.huffingtonpost.com/entry/versace-b...,former versace store clerk sues over secret 'b...,0
1,https://www.huffingtonpost.com/entry/roseanne-...,the 'roseanne' revival catches up to our thorn...,0
2,https://www.theonion.com/mom-starting-to-fear-...,mom starting to fear son's only friend is imag...,1

In [4]:
df = pd.read_csv(r'.venv\1960-2019全球GDP数据.csv', encoding='gbk', )  
df5 = df.head()
df5
df5 = df5.assign(GDP=66) # 可以接收单变量或列表、数组
df5
df

      year   country           GDP
0     1960        美国  543300000000
1     1960        英国   73233967692
2     1960        法国   62225478000
3     1960        中国   59716467625
4     1960        日本   44307342950
...    ...       ...           ...
9925  2019  圣多美和普林西比     418637388
9926  2019        帕劳     268354919
9927  2019      基里巴斯     194647201
9928  2019        瑙鲁     118223430
9929  2019       图瓦卢      47271463

[9930 rows x 3 columns]

In [6]:
df5 = df.head()
display(df5)    # 显示修改前的df5

df5 = df5.assign(GDP=66)
display(df5)    # 显示assign修改后的df5

display(df)

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950

   year country  GDP
0  1960      美国   66
1  1960      英国   66
2  1960      法国   66
3  1960      中国   66
4  1960      日本   66

      year   country           GDP
0     1960        美国  543300000000
1     1960        英国   73233967692
2     1960        法国   62225478000
3     1960        中国   59716467625
4     1960        日本   44307342950
...    ...       ...           ...
9925  2019  圣多美和普林西比     418637388
9926  2019        帕劳     268354919
9927  2019      基里巴斯     194647201
9928  2019        瑙鲁     118223430
9929  2019       图瓦卢      47271463

[9930 rows x 3 columns]

In [11]:
df6 = df.head().copy()
display(df6)

# 1. 修改year列：接收返回值，覆盖原列
df6['year'] = df6.year.replace(1960, 19600)
display(df6)

# 2. 修改country列：日本→扶桑
df6['country'] = df6.country.replace('日本','扶桑')
display(df6)

# 3. 整张表全局替换（所有单元格的1960替换）
df6 = df6.replace(1960, 19600)
display(df6)

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      扶桑   44307342950

    year country           GDP
0  19600      美国  543300000000
1  19600      英国   73233967692
2  19600      法国   62225478000
3  19600      中国   59716467625
4  19600      扶桑   44307342950

    year country           GDP
0  19600      美国  543300000000
1  19600      英国   73233967692
2  19600      法国   62225478000
3  19600      中国   59716467625
4  19600      扶桑   44307342950

    year country           GDP
0  19600      美国  543300000000
1  19600      英国   73233967692
2  19600      法国   62225478000
3  19600      中国   59716467625
4  19600      扶桑   44307342950

In [14]:
display(df.query('country=="帕劳"'))
display(df[df['country']=='帕劳'])

      year country        GDP
4182  1990      帕劳   76888000
4362  1991      帕劳   83855000
4545  1992      帕劳   82451000
4730  1993      帕劳   75907000
4917  1994      帕劳   83527000
5109  1995      帕劳   95237000
5302  1996      帕劳  108203000
5493  1997      帕劳  113213000
5686  1998      帕劳  117320000
5881  1999      帕劳  113485000
6077  2000      帕劳  146297500
6274  2001      帕劳  156907900
6475  2002      帕劳  163184900
6676  2003      帕劳  153963200
6878  2004      帕劳  165186200
7081  2005      帕劳  190452900
7284  2006      帕劳  192382400
7487  2007      帕劳  198897700
7691  2008      帕劳  198283900
7896  2009      帕劳  187522800
8100  2010      帕劳  185943000
8306  2011      帕劳  196911100
8511  2012      帕劳  212397800
8717  2013      帕劳  221117200
8923  2014      帕劳  241669800
9128  2015      帕劳  280457700
9333  2016      帕劳  295065400
9537  2017      帕劳  286106800
9740  2018      帕劳  280435700
9926  2019      帕劳  268354919

      year country        GDP
4182  1990      帕劳   76888000
4362  1991      帕劳   83855000
4545  1992      帕劳   82451000
4730  1993      帕劳   75907000
4917  1994      帕劳   83527000
5109  1995      帕劳   95237000
5302  1996      帕劳  108203000
5493  1997      帕劳  113213000
5686  1998      帕劳  117320000
5881  1999      帕劳  113485000
6077  2000      帕劳  146297500
6274  2001      帕劳  156907900
6475  2002      帕劳  163184900
6676  2003      帕劳  153963200
6878  2004      帕劳  165186200
7081  2005      帕劳  190452900
7284  2006      帕劳  192382400
7487  2007      帕劳  198897700
7691  2008      帕劳  198283900
7896  2009      帕劳  187522800
8100  2010      帕劳  185943000
8306  2011      帕劳  196911100
8511  2012      帕劳  212397800
8717  2013      帕劳  221117200
8923  2014      帕劳  241669800
9128  2015      帕劳  280457700
9333  2016      帕劳  295065400
9537  2017      帕劳  286106800
9740  2018      帕劳  280435700
9926  2019      帕劳  268354919

In [16]:
  display(df.rank(method='average'))
  display(df.rank(method='min'))
  display(df.rank(method='max'))
  display(df.rank(method='dense'))

        year  country     GDP
0       52.0   7912.5  9393.0
1       52.0   8265.5  7900.0
2       52.0   6311.5  7746.0
3       52.0     90.5  7691.0
4       52.0   5032.0  7341.0
...      ...      ...     ...
9925  9838.0   2759.0  1158.0
9926  9838.0   4830.5   855.0
9927  9838.0   3059.5   632.0
9928  9838.0   7145.0   376.0
9929  9838.0   2539.5   152.0

[9930 rows x 3 columns]

        year  country     GDP
0        1.0   7883.0  9393.0
1        1.0   8236.0  7900.0
2        1.0   6282.0  7746.0
3        1.0     61.0  7691.0
4        1.0   5032.0  7341.0
...      ...      ...     ...
9925  9746.0   2750.0  1158.0
9926  9746.0   4816.0   855.0
9927  9746.0   3035.0   632.0
9928  9746.0   7139.0   376.0
9929  9746.0   2525.0   152.0

[9930 rows x 3 columns]

        year  country     GDP
0      103.0   7942.0  9393.0
1      103.0   8295.0  7900.0
2      103.0   6341.0  7746.0
3      103.0    120.0  7691.0
4      103.0   5032.0  7341.0
...      ...      ...     ...
9925  9930.0   2768.0  1158.0
9926  9930.0   4845.0   855.0
9927  9930.0   3084.0   632.0
9928  9930.0   7151.0   376.0
9929  9930.0   2554.0   152.0

[9930 rows x 3 columns]

      year  country     GDP
0      1.0    169.0  9382.0
1      1.0    176.0  7895.0
2      1.0    134.0  7741.0
3      1.0      3.0  7686.0
4      1.0    107.0  7336.0
...    ...      ...     ...
9925  60.0     60.0  1157.0
9926  60.0    101.0   855.0
9927  60.0     67.0   632.0
9928  60.0    152.0   376.0
9929  60.0     55.0   152.0

[9930 rows x 3 columns]